### ISSUE TITLE
[Android] NPE in setMyAvailability

### ISSUE THREAD

**Issue by dalinaum** [realm/RealmPop#12]
Sometimes I get the following message, and I cannot reproduce this yet.

```
04-05 05:16:05.109 2052-2052/realm.io.realmpop E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: realm.io.realmpop, PID: 2052
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'io.realm.RealmAsyncTask io.realm.Realm.executeTransactionAsync(io.realm.Realm$Transaction, io.realm.Realm$Transaction$OnSuccess)' on a null object reference
                                                                     at realm.io.realmpop.controller.GameRoomActivity.setMyAvailability(GameRoomActivity.java:89)
                                                                     at realm.io.realmpop.controller.GameRoomActivity.moveToGame(GameRoomActivity.java:215)
                                                                     at realm.io.realmpop.controller.GameRoomActivity.access$200(GameRoomActivity.java:29)
                                                                     at realm.io.realmpop.controller.GameRoomActivity$1.onChange(GameRoomActivity.java:57)
                                                                     at realm.io.realmpop.controller.GameRoomActivity$1.onChange(GameRoomActivity.java:49)
                                                                     at io.realm.ProxyState.notifyChangeListeners(ProxyState.java:92)
                                                                     at io.realm.ProxyState.access$100(ProxyState.java:31)
                                                                     at io.realm.ProxyState$1.onChange(ProxyState.java:152)
                                                                     at io.realm.ProxyState$1.onChange(ProxyState.java:142)
                                                                     at io.realm.internal.RealmNotifier$RealmObserverPair.onChange(RealmNotifier.java:56)
                                                                     at io.realm.internal.RealmNotifier$RealmObserverPair.access$100(RealmNotifier.java:49)
                                                                     at io.realm.internal.RealmNotifier$1.onCalled(RealmNotifier.java:68)
                                                                     at io.realm.internal.RealmNotifier$1.onCalled(RealmNotifier.java:63)
                                                                     at io.realm.internal.ObserverPairList.foreach(ObserverPairList.java:107)
                                                                     at io.realm.internal.RealmNotifier.didChange(RealmNotifier.java:97)
                                                                     at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                     at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ericmaxwell2003** [comment]
@dalinaum , the code has been refactored considerably since then for "2.0".  I don't believe this is an issue anymore.  The code that produced this stack trace is no longer present.
